### ISSUE TITLE
conflictNotification1

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#10]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L250

     ` "conflictNotification1": "Einige der zu importierenden Nodes sind bereits im Arbeitsbereich vorhanden ",`

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
