### ISSUE TITLE
Komma hinzufügen

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#2]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L135

-> Sie müssen angemeldet sein, um Änderungen übernehmen (deploy) zu können
J.

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
