### ISSUE TITLE
notification.warnings.safe-mode

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#3]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L146
Alternative:
`"<p>Flows sind im abgesicherten Modus gestoppt.</p><p>Flows können bearbeitet und übernommen (deploy) werden, um sie neu zu starten.</p>",`

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
