### ISSUE TITLE
project_empty

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#4]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L152

`      "project_empty": "<p>Das Projekt ist leer.</p><p>Soll ein Standardsatz an Projektdateien erstellen werden? <br/> Andernfalls müssen die Dateien manuell außerhalb des Editors  dem Projekt hinzugefügt werden.</p>",`

**Comment by heikokue** [comment]
ja, indirekte (An)Sprache gefällt mir auch besser

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
