### ISSUE TITLE
git_merge_conflict

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#5]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L154

`"git_merge_conflict" : "<p> Der automatische Merge der Änderungen ist fehlgeschlagen. </p> <p>Die Merge-Konflikte müssen behoben werden und die Ergebnisse ins Repository übertragen werden (commit). </p>"`

**Comment by heikokue** [comment]
Noch besser ohne doppeltes "werden":
`"<p>Der automatische Merge der Änderungen ist fehlgeschlagen.</p><p>Die Merge-Konflikte müssen behoben und die Ergebnisse ins Repository übertragen werden (commit).</p>"`

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
