### ISSUE TITLE
unsupportedVersion

### ISSUE THREAD

**Issue by jwende** [heikokue/node-red#6]
https://github.com/heikokue/node-red/blob/4b2d5040bc709ca4e9b6c8356ebfe7021e533e0d/packages/node_modules/%40node-red/editor-client/locales/de/editor.json#L163

` "unsupportedVersion": "<p>Nicht unterstützte Version von Node.js erkannt</p><p>Es muss ein Upgrade auf das neueste LTS-Release von Node.js durchgeführt werden.</p>",`

**Comment by heikokue** [comment]
@jwende Bitte schließen, wenn OK
